import AppKit
import Testing
@testable import MacotronEngine
@testable import Modules

@MainActor
@Suite("ClipboardHistory")
struct ClipboardHistoryTests {
    private func makeEngine(userOptions: [String: Any]? = nil) -> (Engine, ClipboardModule) {
        let engine = Engine()
        engine.dryRun = true
        if let userOptions {
            engine.configStore["modules"] = ["clipboard": userOptions]
        }
        engine.addModule(ClipboardModule())
        engine.registerAllModules()
        let module = engine.configStore["__clipboardModule"] as! ClipboardModule
        return (engine, module)
    }

    private func copy(_ text: String, to pb: NSPasteboard) {
        pb.clearContents()
        pb.setString(text, forType: .string)
    }

    @Test("history is off until a consumer starts")
    func offByDefault() {
        let (_, module) = makeEngine()
        let pb = NSPasteboard.withUniqueName()
        copy("secret", to: pb)
        module.poll(pb)
        #expect(module.history.isEmpty)
    }

    @Test("calling history() opts in to recording")
    func historyCallOptsIn() {
        let (engine, module) = makeEngine()
        _ = engine.evaluate("macotron.clipboard.history()")
        let pb = NSPasteboard.withUniqueName()
        copy("hello", to: pb)
        module.poll(pb)
        #expect(module.history.count == 1)
        #expect(module.history.first?["text"] as? String == "hello")
    }

    @Test("a clipboard:changed listener opts in to recording")
    func listenerOptsIn() {
        let (engine, module) = makeEngine()
        _ = engine.evaluate(#"$$__on("clipboard:changed", function() {})"#)
        let pb = NSPasteboard.withUniqueName()
        copy("hello", to: pb)
        module.poll(pb)
        #expect(module.history.count == 1)
    }

    @Test("modules.clipboard.history setting opts in")
    func settingOptsIn() {
        let (_, module) = makeEngine(userOptions: ["history": true])
        let pb = NSPasteboard.withUniqueName()
        copy("hello", to: pb)
        module.poll(pb)
        #expect(module.history.count == 1)
    }

    @Test("concealed, transient, and auto-generated types are skipped")
    func concealedSkipped() {
        let (_, module) = makeEngine(userOptions: ["history": true])
        let pb = NSPasteboard.withUniqueName()
        for concealed in [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
        ] {
            pb.clearContents()
            pb.declareTypes([.string, NSPasteboard.PasteboardType(concealed)], owner: nil)
            pb.setString("hunter2", forType: .string)
            module.poll(pb)
        }
        #expect(module.history.isEmpty)
        copy("plain", to: pb)
        module.poll(pb)
        #expect(module.history.count == 1)
    }

    @Test("history() prunes items older than the age cap")
    func ageCap() {
        let (engine, module) = makeEngine(userOptions: ["history": true])
        module.history = [
            ["id": "old", "text": "stale", "kind": "text",
             "ts": (Date().timeIntervalSince1970 - 100_000) * 1000],
            ["id": "new", "text": "fresh", "kind": "text",
             "ts": Date().timeIntervalSince1970 * 1000],
        ]
        let (result, error) = engine.evaluate(
            "macotron.clipboard.history().map(function(i) { return i.id; }).join(',')")
        #expect(error == nil)
        #expect(result == "new")
        #expect(module.history.count == 1)
    }

    @Test("cleanup resets the history() opt-in")
    func cleanupResetsOptIn() {
        let (engine, module) = makeEngine()
        _ = engine.evaluate("macotron.clipboard.history()")
        module.cleanup()
        let pb = NSPasteboard.withUniqueName()
        copy("hello", to: pb)
        module.poll(pb)
        #expect(module.history.isEmpty)
    }
}
