import sys; sys.path.insert(0, '.')
from drive import *
key('esc'); glide(900, 560, 0.1)
p = record("launcher", 16)
combo(OPT, 'space'); time.sleep(0.9)
type_('quar'); time.sleep(2.2)
key('esc'); time.sleep(0.5)
combo(OPT, 'space'); time.sleep(0.7)
type_('12*7+3'); time.sleep(2.0)
key('esc'); time.sleep(0.5)
combo(OPT, 'space'); time.sleep(0.7)
type_('cal'); time.sleep(2.0)
key('esc')
done(p, "launcher")
c.disconnect()
